package-lock.json, package.json, src/repositories/soft-crud.repository.base.ts
As loopback CLI and core packages as has been updated so did a npm update to bring loopback and other packages to their latest version.
Updated the base soft crud repository to include the new signature of the interface. Also updated couple of find functions as their signatures also had been updated in the core library.
New interface takes the 3rd optional parameter of Relations as type object.
As nothing new was implemented, so I ran the existing test cases on my local machine they passed all the tests but failed at some lint thing.
=> updated the package versions and their corresponding effect on the base repository class

.vscode/settings.json, package-lock.json, package.json, src/repositories/soft-crud.repository.base.ts
Fixes security issue with lodash
=> Updated lodash version

package-lock.json, package.json, src/repositories/soft-crud.repository.base.ts
I updated the packages in order to maintain updated with current loopback version, after a update in loopback, I couldn't use this extension because they change a promise type in DefaultCrudRepository
After I updated the packages and handle errors, I executed the tests and they passed
=> updating packages and fixing promise type at soft-crud.repository.base

package-lock.json, package.json, src/error-keys.ts, src/repositories/soft-crud.repository.base.ts
fixed issue of findById returns the record successfully, even if the record is soft deleted in DB.
also new dependency added: @loopback/rest
Fixes #11 
=> findById() fetches the record which is soft deleted in DB

src/repositories/default-transaction-soft-crud.repository.base.ts, src/repositories/index.ts
Added loopback4 transaction soft crud base repo 
Fixed filters re-assignment issue in base repo.
=> Added transaction soft crud base repo

package-lock.json, package.json, src/models/soft-delete-entity.ts, src/repositories/soft-crud.repository.base.ts
Added capability for deleted_on, deleted_by attributes. 
dependency that is required: loopback4-authentication
=> Add capability for deleted_on, deleted_by attributes

.eslintignore, package-lock.json, package.json
RPMS-1734
Updated loopback dependencies
Fixed lint configuration
=> refactor(repository): updated loopback dependencies

package-lock.json, package.json, src/repositories/default-transaction-soft-crud.repository.base.ts, src/repositories/soft-crud.repository.base.ts
Description
Updated versions of All Loopback packages.
Type of change
=> fix(version): updated versions of all loopback packages

README.md, src/repositories/default-transaction-soft-crud.repository.base.ts, src/repositories/soft-crud.repository.base.ts
add the ability to query soft delete records
Fixes # (31,18)
=> feat(repository): add ability to query soft delete records

.nycrc, .prettierignore, package.json, src/__tests__/unit/default-transaction-soft-crud.repository.base.ts, src/repositories/default-transaction-soft-crud.repository.base.ts, src/repositories/soft-crud.repository.base.ts
GH-45
Improved test coverage, also fixed issue in deleteHard methods.
Fixes #45 
=> fix(repository): improve test coverage

src/repositories/default-transaction-soft-crud.repository.base.ts, src/repositories/repo-utils.ts, src/repositories/soft-crud.repository.base.ts
=> refactor(loopback4-soft-delete):  Resolved conflicts and refactored 

src/repositories/default-transaction-soft-crud.repository.base.ts, src/repositories/soft-crud.repository.base.ts
Get count of all instances  of an entity
Fixes #38
=> fix(repository): unable to get count of all instances of an entity

package-lock.json, package.json
GH-0
peer dependencies updated to latest version.
=> fix(chore): peer dependencies update to latest version

package-lock.json
GH-0
soft delete dependencies update
=> fix(chore): soft delete dependencies update

.cz-config.js, package-lock.json, package.json, patches/ramda+0.28.0.patch
- updated all dependencies ( dev as well as peer)
- applied patch for ramda package
- add override section to package json which forces to install deps which have no security vulnerabilities. npm audit gives 0 vulnerabilities
=> chore(deps): update to latest loopback deps and solve security vulnerabilities

package-lock.json, package.json
#57
semantic release of package.
Fixes #57 
=> feat(ci-cd): semantic release

README.md, package-lock.json, src/__tests__/unit/mixin/soft-crud.mixin.unit.ts, src/__tests__/unit/mixin/soft-delete-entity.mixin.unit.ts, src/__tests__/unit/repository/default-transaction-soft-crud.repository.base.ts, src/__tests__/unit/repository/soft-crud.repository.unit.ts, src/index.ts, src/mixins/index.ts, src/mixins/soft-crud.repository.mixin.ts, src/mixins/soft-delete-entity.mixin.ts, src/types.ts, tsconfig.json
added mixin for SoftDeleteEntity, DefaultTransactionRepository and DefaultCrudRepository
Fixes #79 
=> feat(entity): add mixin for SoftDeleteEntity, DefaultTransactionRepository, DefaultCrudRepository

package-lock.json, package.json
#85
update loopback4-authentication version
Fixes #85
=> chore(deps): update loopback4-authentication

src/repositories/soft-crud.repository.base.ts
#87
While using findById there are two database calls causing latency.
combined those into one.
Fixes #87
=> feat(repository): remove multiple db calls for find by id

src/repositories/soft-crud.repository.base.ts
gh-91
Fixed issue with object assignment
Fixes # (issue) GH-91
=> fix(repository): fixed object assignment for filters

README.md, package-lock.json, package.json, src/__tests__/unit/mixin/soft-crud.mixin.unit.ts, src/__tests__/unit/mixin/soft-delete-entity.mixin.unit.ts, src/__tests__/unit/repository/default-transaction-soft-crud.repository.base.ts, src/__tests__/unit/repository/soft-crud.repository.unit.ts, src/mixins/soft-crud.repository.mixin.ts, src/repositories/default-transaction-soft-crud.repository.base.ts, src/repositories/soft-crud.repository.base.ts, src/types.ts
BREAKING CHANGE:
remove dependency of loopback4-authentication
Allow deletedBy user id to be configurable
Fixes #99 
=> feat(repository): allow deletedBy id to be configurable

package-lock.json, package.json
GH-97
updated peer dependencies
Fixes #97 
=> chore(deps): updated peer dependencies

src/release_notes/post-processing.js
now will show correct issue description as well
GH-123
corrected the issue number
now will show correct issue description as well
Fixes #123 
=> fix(chore): corrected the issue number

src/__tests__/unit/mixin/soft-crud.mixin.unit.ts, src/repositories/default-transaction-soft-crud.repository.base.ts, src/repositories/sequelize/sequelize.soft-crud.repository.base.ts, src/repositories/soft-crud.repository.base.ts, src/types.ts
- Adds `countAll` function in soft crud base repositories to support counting all entries including soft deleted ones
GH-144
Fixes #144 
=> feat(repository): add `countAll` method

src/__tests__/unit/repository/default-transaction-soft-crud.repository.base.ts, src/__tests__/unit/repository/soft-crud.repository.unit.ts, src/__tests__/unit/sequelize/sequelize-soft-crud.unit.ts
- Adds unit test cases for transactional, soft-crud and sequelize soft crud repo
GH-146
Fixes #146 
=> test(repository): add missing test cases for `countAll`

README.md
- Added details of additional methods provided by this packages such as for findAll, countAll, deleteHard etc.
GH-148
Fixes #148 
PS: This commit was intentionally marked as type `fix` instead of docs to publish the previously unpublished changes.
=> fix(docs): add details of additional methods provided

src/component.ts
- Resolving sonar code smells to improve quality gate
Fixes # (GH-128)
=> fix(chore): fix sonar code smells

package-lock.json, package.json
- Version 14 of Nodejs reaches its end of life
- BREAKING CHANGE: End of life of Node v14
GH-155
Fixes #155
=> feat(chore): remove support for node v14

README.md, package-lock.json, package.json, src/__tests__/unit/sequelize/sequelize-soft-crud.unit.ts, src/repositories/sequelize/sequelize.soft-crud.repository.base.ts
- Loopback version update
- Changed import path of some files as 'loopback4-sequelize' is now '@loopback/sequelize'
GH-151
Fixes #151
=> chore(deps): loopback version update

.github/workflows/release.yaml, package-lock.json
release will be via workflow
BREAKING CHANGE:
remove support for node 16
GH-179
add github release workflow
Fixes #179 
=> feat(ci-cd): add github release workflow

package-lock.json, package.json
update dependencies and devDependencies for better linting and compatibilty with @loopback/cli
GH-194
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #194 
=> chore(deps): update deps and devDeps

package-lock.json, package.json
BREAKING CHANGE:
Loopback package version update
Update the lb4 dependencies as lb4 dropped support for node 16 or lower
Fixes #197 
=> feat(deps): update lb4 dependencies

.github/workflows/sync-docs.yaml, package-lock.json
since the readme moved to docs folder
GH-00
update readme path in sync docs action
=> chore(ci-cd): update readme path in sync docs action

.github/workflows/main.yaml, .github/workflows/release.yaml, package.json
add the missing ci checks for pr
GH-211
add step to generate changelog
add the missing ci checks for pr
Fixes #211 
=> fix(ci-cd): add step to generate changelog
